THIS VERSION ONLY WORKS WITH IN-PLACE SORTING ALGORITHMS.
TO MAKE YOUR OWN VISUALIZATION, USE THE VISUAL ARRAY CLASS, ALONG WITH ITS METHODS.
COPY THE WORK FLOW OF THE PROVIDED ALGORITHMS IN THE "algorithms.py" FILE.